steps:
#Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
#Menjalankan
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']
#Deploy
- name: 'gcr.io/cloud-builders/npm'
  args: ['app', 'deploy']
